project_management-main/config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }

  namespace :admin do
    get "dashboard", to: "dashboard#index", as: :dashboard                        # Grupları Yönet
    resources :advisors , only: [:new, :create, :destroy]                         # Danışman Ekle (CRUD için)
    resource :system_setting, only: [:edit, :update] 

    resource :setting, only: [:edit, :update, :show] do
      get :export_unassigned_students  
      post :email_unassigned_students 
      post :random_group_students 
      patch :update_group_quota 
    end

    resource :project_setting, only: [:edit, :update] do
      post :assign_random_projects
      patch :rename_groups
      get :export_groups_to_csv
    end

    resources :allowed_students, only: [:new, :destroy,] do
      collection do
        post :import_csv
      end
    end

  end

  namespace :advisor do
    resource :password, only: [:edit, :update], controller: 'passwords'
    get "dashboard", to: "dashboard#index", as: :dashboard
    get 'projects', to: 'projects#dashboard'
    get 'projects/manage', to: 'projects#manage'
    get 'groups', to: 'groups#index'
    
    resources :projects do
      collection do
        get :requests  
      end
    end
     
      resources :project_requests do
        member do
          patch :accept
          patch :reject
        end
      end
      
      resources :project_proposals, only: [:index] do
        member do
          patch :accept
          patch :reject
        end
      end
    resources :groups, only: [:new, :create, :edit, :update, :destroy]
  end
  
  
  namespace :student do
    get "dashboard", to: "dashboard#index"
  
    resources :groups, only: [:index, :new, :create, :show, :destroy] do
      resources :group_members, only: [:create, :destroy]
    end
  
    resources :projects, only: [:index] do
      resources :project_requests, only: [:new, :create]
  
      collection do
        get "published", to: "projects#published", as: :published
        get "proposals", to: "projects#proposals", as: :proposals
      end
    end

    resources :project_proposals, only: [:new, :create]
  end
end 

project_management-main/app/models/project.rb
class Project < ApplicationRecord
  belongs_to :advisor, class_name: 'User', foreign_key: 'advisor_id'
  has_many :project_requests, dependent: :destroy
  has_many :groups, foreign_key: :project_id, dependent: :nullify
  
  validates :title, presence: true
  validates :description, presence: true
  validates :quota, numericality: { greater_than_or_equal_to: 0 }, allow_nil: true 

  after_initialize :set_default_published, if: :new_record?

  def current_application_count
    accepted_group_ids = Group.where(project_id: id).pluck(:id)
    pending_requests = project_requests.where(status: [:pending]).count
  
    pending_requests + accepted_group_ids.count
  end

  def full?
    quota.present? && current_application_count >= quota
  end
  private

  def set_default_published
    self.published ||= true
  end
end

project_management-main/app/controllers/advisor/projects_controller.rb
module Advisor
  class ProjectsController < ApplicationController
    layout "advisor"
    before_action :authenticate_user!  
    before_action :only_advisors       
    before_action :set_project, only: [:edit, :update, :destroy]

    def dashboard
    end

    def requests
      @requests = ProjectRequest.joins(:project).where(status: 'pending', projects: { advisor_id: current_user.id })

    end
    
  
    def manage
      @projects = Project.where(advisor_id: current_user.id)  
    end
    

    def new
      @project = Project.new
    end

    
    def create
      @project = Project.new(project_params)
      @project.advisor_id = current_user.id  
      @project.published = true 
      if @project.save
        redirect_to advisor_projects_manage_path, notice: "Proje başarıyla eklendi."
      else
        render :new
      end
    end
    
  
    def edit
    end

    def update
      if @project.update(project_params)
        redirect_to advisor_projects_manage_path, notice: "Proje başarıyla güncellendi!"
      else
        render :edit, status: :unprocessable_entity
      end
    end
    
    def destroy
      @project.groups.update_all(project_id: nil)
      ProjectRequest.where(project_id: @project.id).destroy_all
      ProjectProposal.where(project_id: @project.id).destroy_all
      @project.destroy
      redirect_to advisor_projects_manage_path, notice: "Proje başarıyla silindi!"
    end

    private

    def only_advisors
      unless current_user&.advisor?
        redirect_to root_path, alert: "Bu sayfaya erişim yetkiniz yok!"
      end
    end

    def set_project
      @project = Project.find_by(id: params[:id], advisor_id: current_user.id)
      redirect_to advisor_projects_manage_path, alert: "Bu projeye erişim yetkiniz yok!" unless @project
    end

    def project_params
      params.require(:project).permit(:title, :description, :quota)
    end
  end
end

project_management-main/app/controllers/student/dashboard_controller.rb
module Student
  class DashboardController < ApplicationController 
    layout "student"
    before_action :only_students
    
    def index
      
    end
  end
end

project_management-main/app/controllers/student/group_members_controller.rb
class Student::GroupMembersController < ApplicationController
  before_action :authenticate_user!

  def create
    @group = Group.find(params[:group_id])
    student = User.find(params[:student_id])

    if student.group.present?
      redirect_to student_groups_path, alert: "Bu öğrenci zaten bir gruba üye."
    else
      GroupMembership.create(group: @group, student: student)
      redirect_to student_groups_path, notice: "#{student.email} gruba eklendi."
    end
  end
end

project_management-main/app/controllers/student/groups_controller.rb
class Student::GroupsController < ApplicationController
  layout "student"
  before_action :authenticate_user!
 

  def index
    @group = current_user.group
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.leader = current_user
    @group.name = "Grup #{SecureRandom.hex(3).upcase}"
  
    quota = SystemSetting.find_by(key: "group_quota")&.value.to_i
    quota = 0 if quota.nil?
    selected_student_ids = (params[:group][:student_ids] || []).reject(&:blank?)
  
    if selected_student_ids.uniq.length != selected_student_ids.length
      flash.now[:alert] = "Aynı öğrenci birden fazla kez eklenemez."
      return render :new
    end

    total_members = selected_student_ids.size + 1
  
    if quota > 0 && total_members > quota
      flash.now[:alert] = "Toplam grup üyesi sayısı kota olan #{quota} kişiyi aşamaz."
      return render :new
    end
  
    if @group.save
      GroupMembership.create(group: @group, student: current_user)
  
      selected_student_ids.each do |student_id|
        GroupMembership.create(group: @group, student_id: student_id)
      end
  
      redirect_to student_groups_path, notice: "Grup başarıyla oluşturuldu."
    else
      render :new
    end
  end
  
  
  def destroy
    @group = Group.find(params[:id])
    if @group.project_id.present?
      redirect_to student_groups_path, alert: "Bu grup bir projeye atanmış. Grup silinemez."
    else
      @group.destroy
      redirect_to student_groups_path, notice: "Grup başarıyla silindi."
    end
  end
  

  private

  def group_params
    params.require(:group).permit(:name, student_ids: [])
  end

  
end

project_management-main/app/controllers/student/project_proposals_controller.rb
# app/controllers/project_proposals_controller.rb
class Student::ProjectProposalsController < ApplicationController
    layout 'student'
    before_action :authenticate_user!
    before_action :set_group
  
    def new
      @project_proposal = ProjectProposal.new
      @advisors = User.where(role: :advisor)
    end
  
    def create
      @project_proposal = ProjectProposal.new(project_proposal_params)
      @project_proposal.group = @group
  
      if @project_proposal.save
        redirect_to proposals_student_projects_path, notice: 'Proje teklifi başarıyla gönderildi.'
      else
        @advisors = User.where(role: advisor)
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def set_group
      @group = current_user.group
    end
  
    def project_proposal_params
      params.require(:project_proposal).permit(:advisor_id, :title, :description)
    end
  end
  

project_management-main/app/controllers/student/project_requests_controller.rb
class Student::ProjectRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_group

  
  def new
    if @group.nil?
      redirect_to student_projects_path, alert: "Projeye başvurmak için bir gruba üye olmalısınız."
    elsif @group.leader != current_user
      redirect_to published_student_projects_path, alert: "Sadece grup lideri başvuru yapabilir."
    elsif ProjectRequest.exists?(group: @group, project: @project)
      redirect_to published_student_projects_path, alert: "Bu projeye zaten başvurdunuz."
    else
      @request = ProjectRequest.new
      render "student/projects/project_requests/new"
      
    end
  end
 

  def create
    if @group.nil?
      redirect_to published_student_projects_path, alert: "Projeye başvurmak için bir gruba üye olmalısınız."
    elsif @group.leader != current_user
      redirect_to published_student_projects_path, alert: "Sadece grup lideri başvuru yapabilir."
    elsif ProjectRequest.exists?(group: @group, project: @project)
      redirect_to published_student_projects_path, alert: "Bu projeye zaten başvurdunuz."
    else
      @request = ProjectRequest.new(project: @project, group: @group)
      if @request.save
        redirect_to published_student_projects_path, notice: "Proje başvurusu başarıyla yapıldı."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  private

  def set_project
    Rails.logger.info "DEBUG: Gelen params => #{params.inspect}"
    
    if params[:project_id].blank?
      Rails.logger.error "HATA: project_id parametresi eksik!"
      redirect_to published_student_projects_path, alert: "Projeye başvururken hata oluştu. Lütfen tekrar deneyin." and return
    end
  
    @project = Project.find_by(id: params[:project_id])
  
    if @project.nil?
      Rails.logger.error "HATA: project_id (#{params[:project_id]}) ile eşleşen proje bulunamadı!"
      redirect_to published_student_projects_path, alert: "Geçersiz proje seçildi." and return
    end
  end



  def set_group
    @group = current_user.group
  end
end

project_management-main/app/controllers/student/projects_controller.rb
module Student
  class ProjectsController < ApplicationController
    before_action :authenticate_user! 
    layout "student"

    def index
      @group = current_user.group
    end

    def published
      excluded_project_ids = ProjectProposal.where.not(project_id: nil).pluck(:project_id)
      @projects = Project.includes(:advisor, :project_requests, :groups)
                         .where(published: true)
                         .where.not(id: excluded_project_ids)
      @group = current_user.group
    end
    

    def proposals
      if current_user.group.nil?
        redirect_to student_projects_path, alert: "Henüz bir gruba atanmadınız." and return
      end
    
      @project_proposals = ProjectProposal.where(group_id: current_user.group.id)
    end
    
    
  end
end

project_management-main/app/views/student/projects/index.html.erb
<% deadline = SystemSetting.find_by(key: 'project_selection_deadline')&.value_as_date %>
<% if deadline.present? %>
  <p><strong>Son proje seçim tarihi:</strong> <%= deadline.strftime("%d.%m.%Y") %></p>
<% end %>

<div class="container mt-5">
  <div class="row justify-content-center">
    <!-- Yayımlanan Projeler Kartı -->
    <div class="col-md-5 mb-4">
      <div class="card text-white bg-dark h-100 shadow-sm" style="cursor: pointer;" onclick="location.href='<%= published_student_projects_path %>'">
        <div class="card-body d-flex flex-column justify-content-center align-items-center">
          <h3 class="card-title">Yayımlanan Projeler</h3>
        </div>
      </div>
    </div>

    <!-- Proje Teklifleri Kartı -->
    <div class="col-md-5 mb-4">
    <div class="card text-white bg-dark h-100 shadow-sm" style="cursor: pointer;" onclick="location.href='<%= proposals_student_projects_path %>'">
      <div class="card-body d-flex flex-column justify-content-center align-items-center">
        <h3 class="card-title">Proje Teklifi</h3>
      </div>
    </div>
  </div>
  </div>
</div>

project_management-main/app/views/student/projects/proposals.html.erb
<% deadline = SystemSetting.find_by(key: 'project_selection_deadline')&.value_as_date %>
<% if deadline.present? && Date.today > deadline %>
  <div class="alert alert-danger">
    Proje seçme süresi sona ermiştir. Artık proje başvurusunda bulunamazsınız.
  </div>
<% else %>
    <h2>Yaptığınız Proje Teklifleri</h2>

    <% group = current_user.group %>
          <% leader_request = ProjectRequest.find_by(group_id: group.id, status: [:pending]) %>
          <% proposal_exists = group.project_proposals.where(status: [:pending]).exists? %>
          <% assigned_to_project = group.project_id.present? %>

    <% disable_button = leader_request || proposal_exists || assigned_to_project%>

    <% if disable_button %>
      <%= button_tag "Yeni Proje Teklifi Oluştur", class: "btn btn-outline-secondary mb-3", disabled: true, title: "Zaten bir başvurunuz veya proje teklifiniz var" %>
    <% else %>
      <%= link_to "Yeni Proje Teklifi Oluştur", new_student_project_proposal_path, class: "btn btn-outline-primary mb-3" %>
    <% end %>

    <% if @project_proposals.any? %>  <!-- Burada herhangi bir proje teklifi var mı diye kontrol ediyoruz -->
      <table class="table table-bordered table-hover">
        <thead>
          <tr class="table table-dark text-white"> 
            <th>Başlık</th>
            <th>Açıklama</th>
            <th>Danışman</th>
            <th>Durum</th>
          </tr>
        </thead>
        <tbody>
          <% @project_proposals.each do |proposal| %> <!-- Teklifler üzerinde döngü yapıyoruz -->
            <tr>
              <td><%= proposal.title %></td>
              <td><%= proposal.description.truncate(100) %></td> <!-- Açıklamayı 80 karakterle sınırladık -->
              <td><%= proposal.advisor.full_name %></td>
              <td>
                <% case proposal.status %>
                <% when "pending" %>
                  <span class="fw-bold text-warning">Beklemede</span>
                <% when "accepted" %>
                  <span class="fw-bold text-success">Kabul Edildi</span>
                <% when "rejected" %>
                  <span class="fw-bold text-danger">Reddedildi</span>
                <% else %>
                  <span class="fw-bold text-secondary"><%= proposal.status.capitalize %></span>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <p>Henüz bir proje teklifinde bulunmadınız.</p>
    <% end %>
<% end %>
<div class="container position-relative">
  <%= link_to "Geri", student_projects_path, class: "btn btn-sm btn-outline-secondary position-absolute", style: "top: 1rem; right: 1rem; z-index: 10;" %>
</div>

project_management-main/app/views/student/projects/published.html.erb
<% deadline = SystemSetting.find_by(key: 'project_selection_deadline')&.value_as_date %>
<% if deadline.present? && Date.today > deadline %>
  <div class="alert alert-danger">
    Proje seçme süresi sona ermiştir. Artık proje başvurusunda bulunamazsınız.
  </div>
<% else %>   
  <h3 class="mb-4">Yayımlanan Projeler</h3>

  <% if @projects.empty? %>
  <div class="alert alert-info">
      Yayımlanan bir proje bulunmamaktadır.
    </div>
  <% else %>
    <table class="table table-bordered table-hover">
      <thead class="thead-dark">
        <tr>
          <th>Danışman</th>
          <th>Proje Başlığı</th>
          <th>Proje Açıklaması</th>
          <th>Başvuru Sayısı / Kontenjan</th>
          <th>Başvuru</th>
        </tr>
      </thead>
      <tbody>
        
        <% @projects.group_by(&:advisor).each do |advisor, projects| %>
          <% advisor_name = "#{advisor&.first_name} #{advisor&.last_name}" || "Bilinmiyor" %>

          <% group = current_user.group %>

          <% if group.present? %>
            <% leader_request = ProjectRequest.find_by(group_id: group.id, status: [:pending]) %>
            <% proposal_exists = group.project_proposals.where(status: [:pending]).exists? %>
            <% assigned_to_project = group.project_id.present? %>

            <% disable_buttons = leader_request.present? || proposal_exists || assigned_to_project %>
            <% is_leader = group.leader_id == current_user.id %>
          <% else %>
            <% disable_buttons = true %>
            <% is_leader = false %>
          <% end %>

          <% projects.each_with_index do |project, index| %>
            <tr>
              <% if index == 0 %>
                <td rowspan="<%= projects.size %>" class="align-middle"><%= advisor_name %></td>
              <% end %>
              <td><%= project.title %></td>
              <td><%= project.description.truncate(80) %></td>
              <td><%= "#{project.current_application_count} / #{project.quota || '∞'}" %></td>
              <td>
                <% if group.nil? %>
                  <%= button_tag "Başvur", class: "btn btn-sm btn-outline-secondary", disabled: true, title: "Başvuru yapabilmek için önce bir grup oluşturmalısınız" %>
                <% elsif project.full? %>
                  <%= button_tag "Başvur", class: "btn btn-sm btn-outline-secondary", disabled: true, title: "Bu proje için kontenjan doldu" %>            
                <% elsif disable_buttons %>
                  <%= button_tag "Başvur", class: "btn btn-sm btn-outline-secondary", disabled: true, title: "Grubunuz zaten bir başvuru yaptı veya teklif gönderdi" %>
                <% elsif !is_leader %>
                  <%= button_tag "Başvur", class: "btn btn-sm btn-outline-secondary", disabled: true, title: "Sadece grup lideri başvurabilir" %>
                <% else %>
                  <%= link_to "Başvur", new_student_project_project_request_path(project), class: "btn btn-sm btn-outline-primary" %>
                <% end %>
              </td>
            </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% end %>

  <h3 class="mt-5 mb-3">Başvurularım</h3>

  <% if current_user.group.nil? || current_user.group.project_requests.empty? %>
    <div class="alert alert-info">
      Mevcut bir başvurunuz bulunmamaktadır.
    </div>
  <% else %>
    <table class="table table-bordered table-hover">
      <thead class="table-dark">
        <tr>
          <th>Proje Adı</th>
          <th>Danışman</th>
          <th>Açıklama</th>
          <th>Durum</th>
        </tr>
      </thead>
      <tbody>
        <% current_user.group.project_requests.includes(:project).each do |request| %>
          <% project = request.project %>
          <% advisor = project.advisor %>
          <tr>
            <td><%= project.title %></td>
            <td><%= "#{advisor&.first_name} #{advisor&.last_name}" || "Bilinmiyor" %></td>
            <td><%= project.description.truncate(80) %></td>
            <td>
              <% case request.status %>
              <% when "pending" %>
                <span class="fw-bold text-warning">Beklemede</span>
              <% when "accepted" %>
                <span class="fw-bold text-success">Kabul Edildi</span>
              <% when "rejected" %>
                <span class="fw-bold text-danger">Reddedildi</span>
              <% else %>
                <span class="fw-bold text-secondary"><%= request.status.capitalize %></span>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>

<% end %>  
<div class="container position-relative">
  <%= link_to "Geri", student_projects_path, class: "btn btn-sm btn-outline-secondary position-absolute", style: "top: 1rem; right: 1rem; z-index: 10;" %>
</div>