project_management-main/config/routes.rb
Rails.application.routes.draw do
  
  devise_scope :user do
    root to: "devise/sessions#new"
  end

  devise_for :users, controllers: {
  registrations: 'users/registrations'
  }

  namespace :admin do
    get "dashboard", to: "dashboard#index", as: :dashboard                        # Grupları Yönet
    resources :advisors , only: [:new, :create, :destroy]                         # Danışman Ekle (CRUD için)
    resource :system_setting, only: [:edit, :update] 

    resource :setting, only: [:edit, :update, :show] do
      get :export_unassigned_students  
      post :email_unassigned_students 
      post :random_group_students 
      patch :update_group_quota 
    end

    resource :project_setting, only: [:edit, :update] do
      post :assign_random_projects
      patch :rename_groups
      get :export_groups_to_csv
    end

    resources :allowed_students, only: [:new, :destroy,] do
      collection do
        post :import_csv
      end
    end

  end

  namespace :advisor do
    resource :password, only: [:edit, :update], controller: 'passwords'
    get "dashboard", to: "dashboard#index", as: :dashboard
    get 'projects', to: 'projects#dashboard'
    get 'projects/manage', to: 'projects#manage'
    get 'groups', to: 'groups#index'
    
    resources :projects do
      collection do
        get :requests  
      end
    end
     
      resources :project_requests do
        member do
          patch :accept
          patch :reject
        end
      end
      
      resources :project_proposals, only: [:index] do
        member do
          patch :accept
          patch :reject
        end
      end
    resources :groups, only: [:new, :create, :edit, :update, :destroy]
  end
  
  
  namespace :student do
    get "dashboard", to: "dashboard#index"
  
    resources :groups, only: [:index, :new, :create, :show, :destroy] do
      resources :group_members, only: [:create, :destroy]
    end
  
    resources :projects, only: [:index] do
      resources :project_requests, only: [:new, :create]
  
      collection do
        get "published", to: "projects#published", as: :published
        get "proposals", to: "projects#proposals", as: :proposals
      end
    end

    resources :project_proposals, only: [:new, :create]
  end
end 

project_management-main/app/models/group.rb
class Group < ApplicationRecord
  belongs_to :leader, class_name: "User"
  has_many :group_memberships, dependent: :destroy
  has_many :students, through: :group_memberships, source: :student
  belongs_to :project , optional: true
  has_many :project_proposals, dependent: :destroy
  has_many :project_requests, dependent: :destroy

  validate :within_group_creation_deadline, on: :create
  validate :within_project_selection_deadline, on: :update

def within_group_creation_deadline
  return if Current.user&.admin?

  deadline_str = SystemSetting.find_by(key: 'group_creation_deadline')
  deadline = deadline_str&.value_as_date
  if deadline.present? && Date.today > deadline
    errors.add(:base, "Grup oluşturma süresi dolmuştur.")
  end
end


def within_project_selection_deadline
  return if Current.user&.admin?

  if project_id_changed? && project_id.present?
    deadline_str = SystemSetting.find_by(key: 'project_selection_deadline')
    deadline = deadline_str&.value_as_date
    if deadline.present? && Date.today > deadline
      errors.add(:base, "Proje seçme süresi dolmuştur.")
    end
  end
end
  

end

project_management-main/app/controllers/advisor/groups_controller.rb
module Advisor
  class GroupsController < ApplicationController
    layout "advisor"
    before_action :authenticate_user!

    def index
      @groups = Group
        .includes(:leader, :students, :project) 
        .joins(:project)
        .where(projects: { advisor_id: current_user.id })
    end

    def destroy
      @group = Group.find(params[:id])
      current_project = @group.project
    
      project_request = ProjectRequest.find_by(group_id: @group.id, project_id: @group.project_id)
      project_proposal = ProjectProposal.find_by(group_id: @group.id, project_id: @group.project_id)
    
      if @group.update(project_id: nil)
        if project_request.present?
          project_request.destroy
        elsif project_proposal.present?
          project_proposal.destroy
          current_project.destroy if current_project.present?
        end        
        redirect_to advisor_groups_path, notice: "Grup silindi."
      else
        redirect_to advisor_groups_path, alert: "Grup silinirken bir hata oluştu."
      end
    end    
  end
end

project_management-main/app/controllers/groups_controller.rb
class GroupsController < ApplicationController
    def create
      @group = Group.new(group_params)
  
      group_quota = SystemSetting.find_by(key: "group_quota")&.value.to_i
  
      selected_student_ids = params[:group][:student_ids].reject(&:blank?)
  
      total_members = selected_student_ids.size + 1  
  
      if group_quota > 0 && total_members > group_quota
        flash[:alert] = "Seçilen öğrenci sayısı, belirlenen grup kontenjanını (#{group_quota}) aşıyor!"
        return redirect_to new_group_path
      end
  
      if @group.save
        @group.students << Student.where(id: selected_student_ids)
        redirect_to groups_path, notice: "Grup başarıyla oluşturuldu."
      else
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def group_params
      params.require(:group).permit(:name)
    end
  end

project_management-main/app/controllers/student/dashboard_controller.rb
module Student
  class DashboardController < ApplicationController 
    layout "student"
    before_action :only_students
    
    def index
      
    end
  end
end

project_management-main/app/controllers/student/group_members_controller.rb
class Student::GroupMembersController < ApplicationController
  before_action :authenticate_user!

  def create
    @group = Group.find(params[:group_id])
    student = User.find(params[:student_id])

    if student.group.present?
      redirect_to student_groups_path, alert: "Bu öğrenci zaten bir gruba üye."
    else
      GroupMembership.create(group: @group, student: student)
      redirect_to student_groups_path, notice: "#{student.email} gruba eklendi."
    end
  end
end

project_management-main/app/controllers/student/groups_controller.rb
class Student::GroupsController < ApplicationController
  layout "student"
  before_action :authenticate_user!
 

  def index
    @group = current_user.group
  end

  def new
    @group = Group.new
  end

  def create
    @group = Group.new(group_params)
    @group.leader = current_user
    @group.name = "Grup #{SecureRandom.hex(3).upcase}"
  
    quota = SystemSetting.find_by(key: "group_quota")&.value.to_i
    quota = 0 if quota.nil?
    selected_student_ids = (params[:group][:student_ids] || []).reject(&:blank?)
  
    if selected_student_ids.uniq.length != selected_student_ids.length
      flash.now[:alert] = "Aynı öğrenci birden fazla kez eklenemez."
      return render :new
    end

    total_members = selected_student_ids.size + 1
  
    if quota > 0 && total_members > quota
      flash.now[:alert] = "Toplam grup üyesi sayısı kota olan #{quota} kişiyi aşamaz."
      return render :new
    end
  
    if @group.save
      GroupMembership.create(group: @group, student: current_user)
  
      selected_student_ids.each do |student_id|
        GroupMembership.create(group: @group, student_id: student_id)
      end
  
      redirect_to student_groups_path, notice: "Grup başarıyla oluşturuldu."
    else
      render :new
    end
  end
  
  
  def destroy
    @group = Group.find(params[:id])
    if @group.project_id.present?
      redirect_to student_groups_path, alert: "Bu grup bir projeye atanmış. Grup silinemez."
    else
      @group.destroy
      redirect_to student_groups_path, notice: "Grup başarıyla silindi."
    end
  end
  

  private

  def group_params
    params.require(:group).permit(:name, student_ids: [])
  end

  
end

project_management-main/app/controllers/student/project_proposals_controller.rb
# app/controllers/project_proposals_controller.rb
class Student::ProjectProposalsController < ApplicationController
    layout 'student'
    before_action :authenticate_user!
    before_action :set_group
  
    def new
      @project_proposal = ProjectProposal.new
      @advisors = User.where(role: :advisor)
    end
  
    def create
      @project_proposal = ProjectProposal.new(project_proposal_params)
      @project_proposal.group = @group
  
      if @project_proposal.save
        redirect_to proposals_student_projects_path, notice: 'Proje teklifi başarıyla gönderildi.'
      else
        @advisors = User.where(role: advisor)
        render :new, status: :unprocessable_entity
      end
    end
  
    private
  
    def set_group
      @group = current_user.group
    end
  
    def project_proposal_params
      params.require(:project_proposal).permit(:advisor_id, :title, :description)
    end
  end
  

project_management-main/app/controllers/student/project_requests_controller.rb
class Student::ProjectRequestsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_project
  before_action :set_group

  
  def new
    if @group.nil?
      redirect_to student_projects_path, alert: "Projeye başvurmak için bir gruba üye olmalısınız."
    elsif @group.leader != current_user
      redirect_to published_student_projects_path, alert: "Sadece grup lideri başvuru yapabilir."
    elsif ProjectRequest.exists?(group: @group, project: @project)
      redirect_to published_student_projects_path, alert: "Bu projeye zaten başvurdunuz."
    else
      @request = ProjectRequest.new
      render "student/projects/project_requests/new"
      
    end
  end
 

  def create
    if @group.nil?
      redirect_to published_student_projects_path, alert: "Projeye başvurmak için bir gruba üye olmalısınız."
    elsif @group.leader != current_user
      redirect_to published_student_projects_path, alert: "Sadece grup lideri başvuru yapabilir."
    elsif ProjectRequest.exists?(group: @group, project: @project)
      redirect_to published_student_projects_path, alert: "Bu projeye zaten başvurdunuz."
    else
      @request = ProjectRequest.new(project: @project, group: @group)
      if @request.save
        redirect_to published_student_projects_path, notice: "Proje başvurusu başarıyla yapıldı."
      else
        render :new, status: :unprocessable_entity
      end
    end
  end

  private

  def set_project
    Rails.logger.info "DEBUG: Gelen params => #{params.inspect}"
    
    if params[:project_id].blank?
      Rails.logger.error "HATA: project_id parametresi eksik!"
      redirect_to published_student_projects_path, alert: "Projeye başvururken hata oluştu. Lütfen tekrar deneyin." and return
    end
  
    @project = Project.find_by(id: params[:project_id])
  
    if @project.nil?
      Rails.logger.error "HATA: project_id (#{params[:project_id]}) ile eşleşen proje bulunamadı!"
      redirect_to published_student_projects_path, alert: "Geçersiz proje seçildi." and return
    end
  end



  def set_group
    @group = current_user.group
  end
end

project_management-main/app/controllers/student/projects_controller.rb
module Student
  class ProjectsController < ApplicationController
    before_action :authenticate_user! 
    layout "student"

    def index
      @group = current_user.group
    end

    def published
      excluded_project_ids = ProjectProposal.where.not(project_id: nil).pluck(:project_id)
      @projects = Project.includes(:advisor, :project_requests, :groups)
                         .where(published: true)
                         .where.not(id: excluded_project_ids)
      @group = current_user.group
    end
    

    def proposals
      if current_user.group.nil?
        redirect_to student_projects_path, alert: "Henüz bir gruba atanmadınız." and return
      end
    
      @project_proposals = ProjectProposal.where(group_id: current_user.group.id)
    end
    
    
  end
end

project_management-main/app/helpers/groups_helper.rb
module GroupsHelper
end

project_management-main/app/views/student/groups/index.html.erb
<% deadline = SystemSetting.find_by(key: 'group_creation_deadline')&.value_as_date %>
<% if deadline.present? && Date.today > deadline %>
  <div class="alert alert-danger">
    Grup oluşturma süresi sona ermiştir. Artık grup oluşturamaz veya silemezsiniz.
  </div>
  <% if @group.present? %>
      <div class="mb-4">
        <p><strong>Grup Adı:</strong> <%= @group.name %></p>
      </div>

      <table class="table table-bordered table-striped">
        <thead class="table-dark">
          <tr>
            <th>Üye Adı Soyadı</th>
            <th>Öğrenci Numarası</th>
            <th>Rol</th>
          </tr>
        </thead>
        <tbody>
          <% @group.students.each do |student| %>
            <tr>
              <td><%= "#{student.first_name} #{student.last_name}" %></td>
              <td><%= "#{student.student_number}" %></td>
              <td>
                <%= student == @group.leader ? "Lider" : "Üye" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
  <% else %>
  <% end %>
<% else %>
    <h2>Grup Yönetimi</h2>
    <% deadline = SystemSetting.find_by(key: 'group_creation_deadline')&.value_as_date %>
    <% if deadline.present? %>
      <p><strong>Son grup oluşturma tarihi:</strong> <%= deadline.strftime("%d.%m.%Y") %></p>
    <% end %>

    <% if @group.present? %>
      <div class="mb-4">
        <p><strong>Grup Adı:</strong> <%= @group.name %></p>
      </div>

      <table class="table table-bordered table-striped">
        <thead class="table-dark">
          <tr>
            <th>Üye Adı Soyadı</th>
            <th>Öğrenci Numarası</th>
            <th>Rol</th>
          </tr>
        </thead>
        <tbody>
          <% @group.students.each do |student| %>
            <tr>
              <td><%= "#{student.first_name} #{student.last_name}" %></td>
              <td><%= "#{student.student_number}" %></td>
              <td>
                <%= student == @group.leader ? "Lider" : "Üye" %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <% if current_user.id == @group.leader_id %>
        <%= button_to "Grubu Sil", student_group_path(@group), method: :delete, class: "btn btn-outline-danger mt-3", data: { turbo_method: :delete } %>
      <% else %>
        <%= button_tag "Grubu Sil", class: "btn btn-outline-danger mt-3", disabled: true, title: "Sadece grup lideri grubu silebilir" %>
      <% end %>

    <% else %>
      <p>Henüz bir grubunuz yok.</p>
      <%= link_to "Yeni Grup Oluştur", new_student_group_path, class: "btn btn-outline-success" %>
    <% end %>
<% end %>

project_management-main/app/views/student/groups/new.html.erb
<h2>Yeni Grup Oluştur</h2>

<%= form_with model: @group, url: student_groups_path, method: :post, local: true do |f| %>
  <h4>Grup Üyeleri</h4>
  
  <!-- Grup lideri (current_user) -->
  <div class="input-group mb-2">
    <input type="text" class="form-control" value="<%= "#{current_user.full_name} - #{current_user.student_number}" %>" disabled>
    <span class="input-group-text bg-secondary text-white">Lider</span>
  </div>

  <div class="form-group">
    <div id="student-selects"></div>
    <button type="button" id="add-student" class="btn btn-outline-secondary mt-2">+ Grup Üyesi Ekle</button>
  </div>

  <%= f.submit "Grubu Oluştur", class: "btn btn-outline-success mt-3" %>
<% end %>

<% if (quota = SystemSetting.find_by(key: "group_quota")&.value.to_i).positive? %>
  <div class="alert alert-info mt-3">
    Grup lideri (siz) dahil olmak üzere en fazla <strong><%= quota %></strong> kişi olabilir.
    Bu nedenle en fazla <strong><%= quota - 1 %></strong> öğrenci ekleyebilirsiniz.
  </div>
<% end %>

<%= javascript_tag do %>
  document.addEventListener("turbo:load", function () {
    const addButton = document.getElementById("add-student");
    const container = document.getElementById("student-selects");

    if (!addButton || addButton.dataset.bound === "true") return;
    addButton.dataset.bound = "true";

    const quota = <%= SystemSetting.find_by(key: "group_quota")&.value.to_i || 0 %>;
    const maxSelectableStudents = quota > 0 ? quota - 1 : 0;

    const students = <%= raw(
      User.where(role: "student").where.not(id: current_user.id).map do |u|
        {
          id: u.id,
          name: "#{u.first_name} #{u.last_name}".strip.presence || u.email,
          stu_no: "#{u.student_number}",
          has_group: u.group.present?
        }
      end.to_json
    ) %>;

    function getCurrentStudentCount() {
      return container.querySelectorAll("select").length;
    }

    function createSelect() {
      const wrapper = document.createElement("div");
      wrapper.classList.add("d-flex", "align-items-center", "mb-2");

      const select = document.createElement("select");
      select.name = "group[student_ids][]";
      select.className = "form-control me-2";
      select.required = true;

      const emptyOption = document.createElement("option");
      emptyOption.value = "";
      emptyOption.text = "Bir öğrenci seçin...";
      select.appendChild(emptyOption);

      students.forEach(function (student) {
        const option = document.createElement("option");
        option.value = student.id;
        option.text = `${student.name} - ${student.stu_no}${student.has_group ? " (Zaten grupta)" : ""}`;
        if (student.has_group) option.disabled = true;
        select.appendChild(option);
      });

      const removeBtn = document.createElement("button");
      removeBtn.type = "button";
      removeBtn.className = "btn btn-outline-danger btn-sm";
      removeBtn.innerText = "❌";
      removeBtn.onclick = () => {
        wrapper.remove();
        if (getCurrentStudentCount() < maxSelectableStudents) {
          addButton.disabled = false;
        }
      };

      wrapper.appendChild(select);
      wrapper.appendChild(removeBtn);

      return wrapper;
    }

    addButton.addEventListener("click", function () {
      if (getCurrentStudentCount() >= maxSelectableStudents) {
        alert("Kotaya ulaştınız! Daha fazla öğrenci ekleyemezsiniz.");
        addButton.disabled = true;
        return;
      }

      container.appendChild(createSelect());

      if (getCurrentStudentCount() >= maxSelectableStudents) {
        addButton.disabled = true;
      }
    });
  });
<% end %>